"""Migração Inicial

Revision ID: 63f30365f7c9
Revises: 
Create Date: 2024-11-19 12:34:02.126841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f30365f7c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('funcionarios',
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_funcionario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios')
    op.drop_table('empresa')
    # ### end Alembic commands ###
